apiVersion: v1
kind: Namespace
metadata:
  name: b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: b
spec:
  loggingRef: b
  syslogNG:
    jsonKeyDelim: '#'
  controlNamespace: b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGFlow
metadata:
  name: all
  namespace: b
spec:
  loggingRef: b
  match:
    regexp:
      pattern: log-generator
      type: string
      value: json#kubernetes#labels#app.kubernetes.io/name
  localOutputRefs:
    - http
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: SyslogNGOutput
metadata:
  name: http
  namespace: b
spec:
  loggingRef: b
  http:
    url: http://example-test-receiver.infra:8080/tenant-b
    headers:
      - "Content-type: application/json"
