apiVersion: v1
kind: Namespace
metadata:
  name: a
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: a
spec:
  loggingRef: a
  fluentd:
    fluentLogDestination: stdout
    fluentOutLogrotate:
      enabled: false
  controlNamespace: a
  watchNamespaces:
    - a
    - a-user
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: all
  namespace: a
spec:
  loggingRef: a
  match:
    - select: {}
  globalOutputRefs:
    - http
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: http
  namespace: a
spec:
  loggingRef: a
  http:
    endpoint: http://example-test-receiver.infra:8080/tenant-a
    content_type: application/json
    buffer:
      type: memory
      timekey: 1s
      timekey_wait: 0s
